#!/usr/bin/env php
<?php
/**
 * Test loader
 *
 * ./test <TestName>
 *
 * @file    test
 *
 * PHP version 5.3.9+
 *
 * @author  Yancharuk Alexander <alex@itvault.info>
 * @date    Сбт Фев 16 17:01:16 2013
 * @copyright The BSD 3-Clause License.
 */

use Veles\AutoLoader;

define('BASE_PATH', realpath(__DIR__));

setlocale(LC_ALL, 'ru_RU.utf8');
date_default_timezone_set('Europe/Moscow');

require BASE_PATH . '/lib/Veles/AutoLoader.php';
AutoLoader::init();
AutoLoader::registerPath(BASE_PATH . '/lib');

if ($argc < 2) {
	throw new Exception('Enter classname as parameter!');
}

$application = "Tests\\$argv[1]";

$application::testDependencies();
$application::run();
$application::showResults();
