#!/usr/bin/env php
<?php
$content = '';

if ($argc < 2) {
	throw new Exception('You need to enter test name');
}

$test_name = $argv[1];
$test_cnt  = isset($argv[2]) ? $argv[2] : 2;
$file_name = "$test_name.php";
$file_path = __DIR__ . "/Tests/$file_name";
$user_name = trim(exec('git config user.name'));
$user_mail = 'alex at itvault dot info';
$license   = 'The BSD 3-Clause License.';
$lic_link  = 'https://tldrlegal.com/license/bsd-3-clause-license-(revised)';
$curr_date = date('D M d H:i:s Y');
$curr_year = date('Y');

$content .= <<<EOT
<?php
/**
 * @todo <Test description here>
 * @file      $file_name
 *
 * PHP version 5.4+
 *
 * @author    $user_name <$user_mail>
 * @copyright © 2013-$curr_year $user_name
 * @date      $curr_date
 * @license   $license
 *            <$lic_link>
 */

namespace Tests;

use Veles\Tools\CliProgressBar;
use Veles\Tools\Timer;
use Application\TestApplication;

/**
 * Class $test_name
 *
 * @author $user_name <$user_mail>
 */
class $test_name extends TestApplication
{
    protected \$repeats = 10000;

	public function run()
	{
		\$repeats = \$this->getRepeats();
EOT;

$i = 0;
while (++$i <= $test_cnt) {
	$content .= <<<EOT


		Timer::reset();
		\$bar = new CliProgressBar(\$repeats);
		for (\$i = 1; \$i <= \$repeats; ++\$i) {
			Timer::start();
			//TODO Place here your code
			Timer::stop();
			\$bar->update(\$i);
		}

		\$this->addResult('ResultName$i', Timer::get());
EOT;
}

$content .= <<<EOT

	}
}
EOT;

file_put_contents($file_path, $content);
